apiVersion: v1
kind: ConfigMap
metadata:
  name: jobvacancyconfig
  labels:
    app: jobvacancy
data:
  RACK_ENV: "production"
  PORT: "3000"
  DATABASE_URL: "jdbc:postgresql://localhost:5432/postgres"
  