version: '2'
services:
  web:
    image: nicopaez/jobvacancy-ruby:1.3.0
    secrets:
      - postgres_db_password
    links:
      - db
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      RACK_ENV: "production"
      DATABASE_URL: "postgres://postgres:Passw0rd!@db:5432/postgres"
    depends_on:
      - db
    networks:
      - internal
      - external
  db:
    image: postgres:14.4-alpine
    secrets:
      - postgres_db_password
    environment:
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres_db_password"
    networks:
      - internal
networks:
  internal:
  external:
secrets:
  postgres_db_password:
    file: ./postgres_db_password.txt
  database_url:
    file: ./database_url.txt